molecalc/views/calc_views.py
import flask
from flask import request, send_file

import io
import datetime
import hashlib
import logging
import re
import numpy as np

from rdkit import Chem
from rdkit.Chem import AllChem

from molecalc.infrastructure.view_modifiers import response
from molecalc.infrastructure.settings import SETTINGS
import molecalc.data.db_session as db_session
from molecalc.data.gamess_calculation import GamessCalculation
from molecalc.services.io_file_service import get_calc_io_file
from molecalc.lib import gamess

from ppqm import chembridge


_logger = logging.getLogger("molecalc:calc_views")

bp = flask.Blueprint('calc', __name__, template_folder='../templates')


@bp.route('/calculations_download/<string:hashkey>/<string:calc>/<string:iofile>',
          methods=['GET', 'POST'])
# @response(template_file='calculation/calculation.html')
def download_gamess_io(hashkey: str, calc: str, iofile: str):
    match calc:
        case 'opt':
            filename = f'optimization_{hashkey}.{iofile}'
        case 'vib':
            filename = f'vibrations_{hashkey}.{iofile}'
        case 'orb':
            filename = f'orbitals_{hashkey}.{iofile}'
        case _:
            err_msg = 'Unknown calculation type "{calc}"'
            _logger.error(err_msg)
            return {
                "error": "999",
                "message": f"Internal server error: {err_msg}",
            }

    f = get_calc_io_file(hashkey, calc, iofile)

    # return flask.Response(f,
    #     mimetype='text/plain',
    #     direct_passthrough=True,
    #     headers={'Content-disposition': f'attachment; filename={filename}'})

    return send_file(f,
                     mimetype='text/plain',
                     as_attachment=True,
                     download_name=filename)


@bp.route('/calculations')
@bp.route('/calculations/<string:hashkey>')
@response(template_file='calculation/calculation.html')
def calculation(hashkey: str):
    session = db_session.create_session()
    try:
        this_calculation = session.query(GamessCalculation) \
            .filter_by(hashkey=hashkey) \
            .first()
    finally:
        session.close()

    if this_calculation is None:
        raise flask.abort(404)
    if hashkey == "404":
        raise flask.abort(404)

    results = gamess.results.view_calculation(this_calculation)
    return results


@bp.post('/ajax/_submit_quantum')
def ajax_submit_quantum():

    # print(20*'>')
    # print('request.method: ', request.method)
    # print('request.get_data(): ', request.get_data())
    # print('request.form: ', request.form)
    # print('request.values: ', request.values)
    # print(20 * '>')

    if 'sdf' not in request.form:
        return {
                "error": "Error 132 - sdf key error",
                "message": "Error. Missing information.",
            }

    if 'theory_level' not in request.form:
        return {
                "error": "Error XXX - theory level key error",
                "message": "Error. Missing information.",
            }

    # settings = request.registry.settings
    # TODO: Need replacement statement for obtaining (app?) settings for Flask

    # Check if user is someone who is a known misuser
    # user_ip = request.remote_addr
    # if (
    #     constants.COLUMN_BLOCK_IP in settings
    #     and user_ip in settings[constants.COLUMN_BLOCK_IP]
    # ):
    #     return {
    #         "error": "Error 194 - blocked ip",
    #         "message": "IP address has been blocked for misuse",
    #     }

    # if not request.POST:
    #     return {
    #         "error": "Error 128 - empty post",
    #         "message": "Error. Empty post.",
    #     }

    # Get coordinates from request
    sdfstr = request.form["sdf"].encode("utf-8")

    # Is this 2D or 3D?
    add_hydrogens = request.form.get("add_hydrogens", "1")
    add_hydrogens = add_hydrogens == "1"

    # Get theory level
    theory_level = request.form.get('theory_level', 'pm3')
    _logger.info(f'Selected theory level: "{theory_level}"')

    # TODO Use ChemSpider and RDKit/MolVS for chemical name things
    # Get IUPAC name (if available)
    iupac_name = request.form.get('iupac_name', 'N/A')
    _logger.info(f'IUPAC Name: "{iupac_name}"')

    # # Get SMILES name (if available)
    # smiles_name = request.form.get('smiles_name', 'N/A')
    # _logger.info(f'SMILES Name: "{smiles_name}"')

    # Get "trivial" name (if available)
    trivial_name = request.form.get('trivial_name', 'N/A')
    _logger.info(f'Trivial Name: "{trivial_name}"')

    # Get rdkit
    molobj, status = chembridge.sdfstr_to_molobj(sdfstr, return_status=True)

    if molobj is None:
        status = status.split("]")
        status = status[-1]
        status = re.sub(r"\# [0-9]+", "", status)
        return {"error": "Error 141 - rdkit error", "message": status}

    try:
        molobj.GetConformer()
    except ValueError:
        # Error
        return {
            "error": "Error 141 - rdkit error",
            "message": (
                "Error. Server was unable to generate "
                "conformations for this molecule"
            ),
        }

    # If hydrogens not added, assume graph and optimize with forcefield
    atoms = chembridge.molobj_to_atoms(molobj)

    if 1 not in atoms and add_hydrogens:
        molobj = Chem.AddHs(molobj)
        AllChem.EmbedMultipleConfs(molobj, numConfs=1)
        chembridge.molobj_optimize(molobj)

    atoms = chembridge.molobj_to_atoms(molobj)

    # TODO Check lengths of atoms
    # TODO Define max in settings
    max_atoms = 50
    (heavy_atoms,) = np.where(atoms != 1)
    if len(heavy_atoms) > max_atoms:
        return {
            "error": "Error 194 - max atoms error",
            "message": f"Stop Casper. Max {max_atoms} heavy atoms.",
        }

    # Fix sdfstr
    sdfstr = sdfstr.decode("utf8")
    for _ in range(3):
        i = sdfstr.index("\n")
        sdfstr = sdfstr[i+1:]
    sdfstr = "\n" * 3 + sdfstr

    # Inject numerical calculation parameters (e.g., "theory_level") in
    # the generated hashkey so the existence of a calculation depends not only
    # only on the input structure but also the selected numerical inputs
    # TODO CHECK THIS, SEAN --- this is probably causing that error with N#N
    calc_str = f'{sdfstr}\n{theory_level}'

    # hash on sdf (conformer)
    hshobj = hashlib.md5(calc_str.encode())
    hashkey = hshobj.hexdigest()

    # Check if hash/calculation already exists in data
    session = db_session.create_session()
    try:
        this_calculation = session.query(GamessCalculation) \
            .filter_by(hashkey=hashkey) \
            .first()
    finally:
        session.close()

    # If calculation already exists, return
    if this_calculation is not None:
        msg = {"hashkey": hashkey}
        this_calculation.created = datetime.datetime.now()
        _logger.info(f"{hashkey} exists")
        return msg

    # The calculation is valid and does not exist, pass to pipeline
    _logger.info(f"{hashkey} create")

    molecule_info = {"sdfstr": sdfstr, "molobj": molobj, "hashkey": hashkey}
    calc_settings = {'theory_level': theory_level}

    try:
        msg, new_calculation = gamess.pipelines.calculation_pipeline(
            molecule_info, calc_settings)
    except Exception as e:
        sdfstr = chembridge.molobj_to_sdfstr(molobj)
        _logger.error(f"{hashkey} PipelineError", exc_info=True)
        _logger.error(sdfstr)
        print(e)

        return {
            "error": "293",
            "message": "Internal server error. Uncaught exception in calculation pipeline.",
        }

    print(20 * '>')
    print(new_calculation)
    print(20 * '>')

    # Add calculation to the database
    if new_calculation is not None:
        session = db_session.create_session()
        session.add(new_calculation)
        session.commit()
        session.close()

    return msg

molecalc/templates/calculation/calculation.html
<!DOCTYPE html>
<html lang="en">
<head>

  <title>MoleCalc</title>
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">

  {% include 'shared/_header.html' %}

  {% include 'jsmol/head.html' %}

  <script type="text/javascript" src="{{ url_for('static', filename='js/og/calculation.js') }}"></script>

</head>
<body>

<section class="molecalc calculation">

    {% include 'shared/_appicon.html' %}

    <section class="mc-mobile-navigation toggle700 btnHeader left">
        <a class="button icon btnSidebar" href="#calcmenu">
            <i class="fas fa-bars"></i>
        </a>
    </section>

    {% include 'shared/_menu.html' %}
    {% include 'shared/_footer.html' %}

    <!-- content -->

    <section class="mc-content calculation">

        <section class="calc-menu sidebar" id="calcmenu">

            <section class="sidebar-cover"></section>
            <section class="sidebar-background btnCloseSidebar" href="#calcmenu"></section>

            <section class="sidebar-wrapper"> <!-- sidebar wrapper -->

                <section class="toolset toggle700">
                    <a class="button icon btnCloseSidebar" href="#calcmenu">
                        <i class="fas fa-times"></i>
                    </a>
                    <a class="button btnSidebar menu" href="#nav">Menu</a>
                </section>

                <ul>
                    <li><a href="#/energies"  class="energies active">Thermochemistry</a></li>
                    <li><a href="#/vibrations" class="vibrations">Vibrational Modes</a></li>
                    <li><a href="#/orbitals" class="orbitals">Molecular Orbitals</a></li>
                    <!--<li><a href="#/solvation" class="solvation">Polarity and Solvation</a></li>-->
                </ul>

            </section> <!-- sidebar wrapper -->
        </section>

        <section class="calc calc-energies active tab-energies onecol">
            <h2>Ideal Gas Thermochemistry</h2>
            {% include 'calculation/section_thermo.html' %}
        </section>

        <section class="calc calc-vibration tab-vibrations">
            <h2>Vibrational Modes</h2>
            {% include 'calculation/section_vibrations.html' %}
        </section>

        <section class="calc calc-orbitals tab-orbitals">
            <h2>Molecular Orbitals</h2>
            {% include 'calculation/section_orbitals.html' %}
        </section>

{#        <section class="calc calc-orbitals tab-solvation">#}
{#            <h2>Polarity and Solvation</h2>#}
{#            {% include 'calculation/section_solvation.html' %}#}
{#        </section>#}

    </section>
    <!-- end content -->

</section>

<section class="hidden"></section>

</body>
</html>

molecalc/templates/calculation/section_orbitals.html
<script type="text/javascript">
    var sdf = `{{sdf}}`;
    var orbMolecule = `{{orbitalstxt}}`;
</script>

<script type="text/javascript">

var jmolOrb;
var orbInfo1 = {
    height: '100%',
    width: '100%',
    j2sPath: "/static/external/jsmol/j2s",
    use: 'HTML5',
    console: "jmol_orb_infodiv",
    disableInitialConsole: true,
    allowJavaScript: true,
    debug: false,
};


waitForElement('#jmolOrb_appletdiv', function() {
    jsmolSetMol(jmolOrb, orbMolecule);
    Jmol.script(jmolOrb, 'color echo black; font echo 16 sanserif;set echo top right;');
    Jmol.script(jmolOrb, 'echo "{{ iupac_name }} ({{ theorylvl }})"');

    Jmol.script(jmolOrb, 'color echo black; font echo 16 sanserif;set echo bottom right;');
    Jmol.script(jmolOrb, 'echo "{{ orbitals | first }} eV"');

    Jmol.script(jmolOrb, 'mo TITLEFORMAT ""');
    Jmol.script(jmolOrb, 'mo 1');
    Jmol.script(jmolOrb, 'frame 1');
    Jmol.script(jmolOrb, 'set bondRadiusMilliAngstroms 100; set multipleBondSpacing -0.3');
	Jmol.script(jmolOrb, 'centerAt average 0.0 0.0 0.0');
});


$(function() {
    $sidebars = $(".sidebar");

    // Balls on off
    $('#spacefill_switch_orb').on('change', function() {
        var checked = $(this).prop('checked');
        var rel;
        if(checked) {
            rel = 'on; spacefill 24%;';
        }
        else {
            rel = 'off';
        }
        Jmol.script(jmolOrb, 'cpk '+rel);
    }).trigger('change');

    // Show Orbital
    $('.orbital_levels a').on('click', function() {
        // Check for getProperty fileName
        var orbital = $(this).attr('rel');
        var orbEnergy = $(this).parent().parent().find('.energy').html();
        Jmol.script(jmolOrb, 'mo '+orbital);
        Jmol.script(jmolOrb, 'frame 1');
        Jmol.script(jmolOrb, 'echo "' + orbEnergy + '"');
        $sidebars.removeClass("active");
        return false;
    });
});

</script>


<div class="toggle700 calcOptionMenu">
    <a class="button highlight btnSidebar" href="#calcOrbitals">
        <!-- <i class="fas fa&#45;atom"></i> -->
        Orbitals
    </a>
</div>

<section class="options sidebar" id="calcOrbitals">

    <section class="sidebar-cover"></section>
    <section class="sidebar-background btnCloseSidebar" href="#calcOrbitals"></section>

    <section class="sidebar-wrapper"> <!-- sidebar wrapper -->

    <section class="toolset toggle700">
        <a class="button icon btnCloseSidebar" href="#calcOrbitals">
            <i class="fas fa-times"></i>
        </a>
    </section>

    <table>
        <tr>
            <td>Sticks and balls</td>
            <td class="center">
            <div class="onoffswitch">
            <input autocomplete="off"
                   type="checkbox"
                   class="onoffswitch-checkbox"
                   id="spacefill_switch_orb"
                   name="spacefill_switch_orb"
                   checked>
            <label class="onoffswitch-label" for="spacefill_switch_orb">
            <div class="onoffswitch-inner"></div>
            <div class="onoffswitch-switch"></div>
            </label>
            </div>
            </td>
        </tr>

        <tr>
          <td>GAMESS Input</td>
          <td class="center">
            <div>
                <a class="button"
                   href="{{ url_for('calc.download_gamess_io', hashkey=hashkey, calc='orb', iofile='inp') }}">
                  <i class="fa fa-download"></i>
                  orbitals.inp
                </a>
            </div>
          </td>
        </tr>
        <tr>
          <td>GAMESS Output</td>
          <td class="center">
            <div>
                <a class="button"
                   href="{{ url_for('calc.download_gamess_io', hashkey=hashkey, calc='orb', iofile='out') }}">
                  <i class="fa fa-download"></i>
                  orbitals.out
                </a>
            </div>
          </td>
        </tr>
    </table>

    <ul class="data orbital_levels">
    {% for energy in orbitals %}
        <li>
            <span class="index txt">{{loop.index}}</span>
            <span class="energy txt">{{ energy }} eV</span>
            <span class="action"><a href="#!" rel="{{loop.index}}"><i
                    class="fas fa-arrow-circle-right"></i></a></span>
        </li>
    {% endfor %}
    </ul>

    </section> <!-- sidebar wrapper -->
</section>

<section class="view">

    <div class="jsmol" style="width: 100%;height: 100%;">
        <script type="text/javascript">
            jmolOrb = Jmol.getApplet("jmolOrb", orbInfo1);
            Jmol.script(jmolOrb, 'background "#ffffff"');
            Jmol.script(jmolOrb, 'set bondRadiusMilliAngstroms 100; set multipleBondSpacing -0.3');
        </script>
    </div>

</section>

molecalc/templates/calculation/section_thermo.html
<!--<p style="z-index=10;">-->
<!--  Thermodynamics for molecular gas form at STP.-->
<!--  &lt;!&ndash; Would be nice to include the molecule name here... &ndash;&gt;-->
<!--</p>-->
  <!-- <h3>at 298.15 K and standard pressure</h3> -->

<script type="text/javascript">

    var sdf = `{{sdf}}`;
    var optMolecule = `{{outtxt_opt}}`;

    var jmolOpt;
    var optInfo1 = {
        height: '100%',
        width: '100%',
        j2sPath: "/static/external/jsmol/j2s",
        use: 'HTML5',
        disableInitialConsole: true,
        allowJavaScript: true,
        debug: false,
    };

    waitForElement('#jmolOpt_appletdiv', function() {
        jsmolSetMol(jmolOpt, optMolecule);
        Jmol.script(jmolOpt, 'color echo black; font echo 16 sanserif;set echo top right;echo echo test;');
        Jmol.script(jmolOpt, 'echo "{{ iupac_name }} ({{ theorylvl }})"');
        {#jsmolSetMol(jmolOpt, sdf);#}
        {#Jmol.script(jmolOpt, 'set appendNew true');#}
        {#Jmol.script(jmolOpt, "load append trajectory '"+optMolecule+"';");#}

        Jmol.script(jmolOpt, 'set bondRadiusMilliAngstroms 100; set multipleBondSpacing -0.3');
        Jmol.script(jmolOpt, 'centerAt average 0.0 0.0 0.0');
        Jmol.script(jmolOpt, 'animation off');
        Jmol.script(jmolOpt, 'animation fps 15');
        Jmol.script(jmolOpt, 'animation mode palindrome 0.75 0.25');
        Jmol.script(jmolOpt, 'frame LAST');
    });

$(function() {
    $sidebars = $(".sidebar");

    // Select starting or final structure
    $('#frame_selector').on('change', function() {
        var checked = $(this).prop('checked');
        var rel;
        if(checked) {
            rel = '1';
        } else {
            rel = 'LAST';
        }
        Jmol.script(jmolOpt, 'frame '+rel);
    }).trigger('change');

    // Animation on off
    $('#optimization_switch').on('change', function() {
        var checked = $(this).prop('checked');
        var rel;
        if(checked) {
            rel = 'on';
        } else {
            rel = 'off';
        }
        Jmol.script(jmolOpt, 'animation '+rel);
    }).trigger('change');

    // Balls on off
    $('#spacefill_switch_opt').on('change', function() {
        var checked = $(this).prop('checked');
        var rel;
        if(checked) {
            rel = 'on; spacefill 24%;';
        } else {
            rel = 'off';
        }
        Jmol.script(jmolOpt, 'cpk '+rel);
    }).trigger('change');

    // Display first/last frame of optimization trajectory
    $('.opt_frame').on('click', function() {
        // Check for getProperty fileName
        var optframe = $(this).attr('rel');
        Jmol.script(jmolOpt, 'frame '+optframe);
        $sidebars.removeClass("active");
        return false;
    });

    // View optimization animation
    $('.optmol_traj').on('click', function() {
        // Check for getProperty fileName
        var optmol = $(this).attr('rel');
        Jmol.script(jmolOpt, 'animation '+optmol);
        $sidebars.removeClass("active");
        return false;
    });
});

</script>


<div class="toggle700 calcOptionMenu">
    <a class="button highlight btnSidebar" href="#calcOptimization">
        Thermochemistry
        <!-- <i class="fas fa&#45;plus"></i> -->
    </a>
</div>

<section class="options sidebar" id="calcOptimization">

    <section class="sidebar-cover"></section>
    <section class="sidebar-background btnCloseSidebar" href="#calcOptimization"></section>

    <section class="sidebar-wrapper"> <!-- sidebar wrapper -->

        <section class="toolset toggle700">
            <a class="button icon btnCloseSidebar" href="#calcOptimization">
                <i class="fas fa-times"></i>
            </a>
        </section>

    <table>
    <tbody>
    <td width="50%">Select Frame</td>
      <td class="center">
        <div class="firstlastswitch">
            <input autocomplete="off"
                   type="checkbox"
                   class="firstlastswitch-checkbox"
                   id="frame_selector"
                   name="frame_selector">
            <label class="firstlastswitch-label" for="frame_selector">
                <div class="firstlastswitch-inner"></div>
                <div class="firstlastswitch-switch"></div>
            </label>
        </div>
      </td>
    </tr>

    <tr><!-- <h3>at 298.15 K and standard pressure</h3> -->
      <td width="50%">Optimization trajectory</td>
      <td class="center">
        <div class="onoffswitch">
            <input autocomplete="off"
                   type="checkbox"
                   class="onoffswitch-checkbox"
                   id="optimization_switch"
                   name="optimization_switch">
            <label class="onoffswitch-label" for="optimization_switch">
                <div class="onoffswitch-inner"></div>
                <div class="onoffswitch-switch"></div>
            </label>
        </div>
      </td>
    </tr>

    <tr>
      <td>Sticks and balls</td>
      <td class="center">
        <div class="onoffswitch">
            <input autocomplete="off"
                   type="checkbox"
                   class="onoffswitch-checkbox"
                   id="spacefill_switch_opt"
                   name="spacefill_switch_opt"
                   checked>
            <label class="onoffswitch-label" for="spacefill_switch_opt">
                <div class="onoffswitch-inner"></div>
                <div class="onoffswitch-switch"></div>
            </label>
        </div>
      </td>
    </tr>

    <tr>
      <td>GAMESS Input</td>
      <td class="center">
        <div>
            <a class="button"
               href="{{ url_for('calc.download_gamess_io', hashkey=hashkey, calc='opt', iofile='inp') }}">
              <i class="fa fa-download"></i>
              optimization.inp
            </a>
        </div>
      </td>
    </tr>
    <tr>
      <td>GAMESS Output</td>
      <td class="center">
        <div>
            <a class="button"
               href="{{ url_for('calc.download_gamess_io', hashkey=hashkey, calc='opt', iofile='out') }}">
              <i class="fa fa-download"></i>
              optimization.out
            </a>
        </div>
      </td>
    </tr>
    </tbody>
    </table>

    <div class="tbls_container">
        <div class="tbl_container">
          <table>
            <tr><td class="center" colspan="3" style="font-weight:bold">Ideal Gas at 298.13 K</td></tr>
            <!-- <tr><td class="center" style="width:50%">Property</td><td style="width:25%" class="center">Value</td><td style="width:25%" class="center">Unit</td></tr> -->
            <tr><td>Std. Enthalpy of Formation</td><td class="right">{{enthalpy}}</td><td class="right">kJ mol<sup>-1</sup></td><tr></tr>
            <tr><td>Speed of Sound</td><td class="right">{{sound_speed}}</td><td class="right">m/s</td><tr>
            <tr><td>Adiabatic Index</td><td class="right">{{adiabatic_index}}</td><td></td><td class="right"></td><tr>
          </table>
        </div>

        <div class="tbl_container">
          <table>
            <tr><td class="center" colspan="3" style="font-weight:bold">Enthalpy</td></tr>
            <!-- <tr><td class="center" style="width:50%">Property</td><td style="width:25%" class="center">Value</td><td style="width:25%" class="center">Unit</td></tr> -->
            <tr><td>Translational</td><td class="right">{{h_trans}}</td><td class="right">kJ mol<sup>-1</sup> </td><tr>
            <tr><td>Rotational</td><td class="right">{{h_rotat}}</td><td class="right">kJ mol<sup>-1</sup> </td><tr>
            <tr><td>Vibrational</td><td class="right">{{h_vibra}}</td><td class="right">kJ mol<sup>-1</sup></td><tr>
            <tr><td>Total</td><td class="right">{{h_total}}</td><td class="right">kJ mol<sup>-1</sup></td><tr>
          </table>
        </div>

        <div class="tbl_container">
          <table>
            <tr><td class="center" colspan="3" style="font-weight:bold">Heat Capacity at Constant Volume</td></tr>
            <!-- <tr><td class="center" style="width:50%">Property</td><td style="width:25%" class="center">Value</td><td style="width:25%" class="center">Unit</td></tr> -->
            <tr><td>Translational</td><td class="right">{{cv_trans}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
            <tr><td>Rotational</td><td class="right">{{cv_rotat}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
            <tr><td>Vibrational</td><td class="right">{{cv_vibra}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
            <tr><td>Total</td><td class="right">{{cv_total}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
          </table>
        </div>

        <div class="tbl_container">
          <table>
            <tr><td class="center" colspan="3" style="font-weight:bold">Heat Capacity at Constant Pressure</td></tr>
            <!-- <tr><td class="center" style="width:50%">Property</td><td style="width:25%" class="center">Value</td><td style="width:25%" class="center">Unit</td></tr> -->
            <tr><td>Translational</td><td class="right">{{cp_trans}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
            <tr><td>Rotational</td><td class="right">{{cp_rotat}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
            <tr><td>Vibrational</td><td class="right">{{cp_vibra}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
            <tr><td>Total</td><td class="right">{{cp_total}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
          </table>
        </div>

        <div class="tbl_container">
          <table>
            <tr><td class="center" colspan="3" style="font-weight:bold">Entropy</td></tr>
            <!-- <tr><td class="center" style="width:50%">Property</td><td style="width:25%" class="center">Value</td><td style="width:25%" class="center">Unit</td></tr> -->
            <tr><td>Translational</td><td class="right">{{s_trans}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
            <tr><td>Rotational</td><td class="right">{{s_rotat}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
            <tr><td>Vibrational</td><td class="right">{{s_vibra}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
            <tr><td>Total</td><td class="right">{{s_total}}</td><td class="right">J mol<sup>-1</sup> K<sup>-1</sup></td><tr>
          </table>
        </div>
    </div>

    </section> <!-- sidebar wrapper -->
</section>

<section class="view">

    <div class="jsmol" style="width: 100%;height: 100%;">
        <script type="text/javascript">
            jmolOpt = Jmol.getApplet("jmolOpt", optInfo1);
            Jmol.script(jmolOpt, 'background "#ffffff"');
        </script>
    </div>

</section>